### PR TITLE
Add k3s GitHub

### PR DESCRIPTION
**Pull request by DrummyFloyd**
becasue i saw many ppl asking for the github templates, there it is 

still need some test especially on TF parts 

- [x] fix some gitlab template based on  https://github.com/kubefirst/gitops-template/pull/771

- [x] fix `TF_VAR_ssh_private_key` , now passed the content from ARG to `K1-API `as `TF_VAR`  https://github.com/kubefirst/kubefirst-api/pull/353

### CODE REVIEW

**Comment by DrummyFloyd** [comment]
> We won't be able to merge this yet as to add the GitHub support, we also need to update the https://github.com/kubefirst/kubefirst-api and https://github.com/kubefirst/kubefirst-api unless it was done already when you added K3s support. I need to check that first.

if i remember well, it should already be on the code 

but yes could be great to check =)

**Comment by DrummyFloyd** [comment]
the K3S tf provider is pinned so not a version provider issue 

but if you took the exact same command as the doc say , there is some issue upon some parameters

`github` stuff with `gitlab` stuff, dunno

**Comment by fharper** [comment]
Oh yeah no, I use the correct GitLab parameters. I'll fix the docs. My question was mostly about the IPs since it's where the errors are. I created the VMs on Civo also, but it should work with any VMs anyway no? I would have assumed the issue was on my side, but the error is from Terraform while running the kubefirst command, not the script Jared created.

**Comment by DrummyFloyd** [comment]
> Oh yeah no, I use the correct GitLab parameters. I'll fix the docs. My question was mostly about the IPs since it's where the errors are. I created the VMs on Civo also, but it should work with any VMs anyway no? I would have assumed the issue was on my side, but the error is from Terraform while running the kubefirst command, not the script Jared created.

if something change, upon the `detokenize` stuff, for me it should be related to this PR
https://github.com/kubefirst/kubefirst-api/commit/c9da2b8cc10d60b63960b6635242bd1e36b1c53d

**Comment by maxiar** [comment]
Hi! Any News?

**Comment by DrummyFloyd** [comment]
> Hi! Any News?

i think it's still review =/ can't do nothing about it ^^

**Comment by fharper** [comment]
Sorry, the team is super busy, and I was on vacation. I had an issue with this integration when I tested. We quickly checked before I left, and I think we found the issue. I'll give it another go as soon as I'm done catching up on the last weeks.

@maxiar : note that you can try it yourself if you really need it asap. You'll need to use a custom `gitops-template` repository pointing to that branch. See https://docs.kubefirst.io/k3s/explore/gitops#using-your-own-gitops-template-repository-fork

**Comment by maxiar** [comment]
> Sorry, the team is super busy, and I was on vacation. I had an issue with this integration when I tested. We quickly checked before I left, and I think we found the issue. I'll give it another go as soon as I'm done catching up on the last weeks.
> 
> @maxiar : note that you can try it yourself if you really need it asap. You'll need to use a custom `gitops-template` repository pointing to that branch. See https://docs.kubefirst.io/k3s/explore/gitops#using-your-own-gitops-template-repository-fork

Perfect! Good Vacations well deserved!! I will try to install the cluster using this branch "add-k3s-github", but we have a question, what version of the kuberfirst cli must be use? the latest? or compile from another WIP branch? Sorry for the dummy comment.. :)

**Comment by fharper** [comment]
When adding GitLab support, Drummy made sure GitHub was functional with the kubefirst CLI, so you only need to use this branch. To do so, add these flags (more information on the flags in the docs link I shared in my previous message) to the command for K3s (see https://docs.kubefirst.io/k3s/quick-start/install/cli/#create-your-new-kubefirst-cluster)

`--gitops-template-url https://github.com/DrummyFloyd/gitops-template --gitops-template-branch add-k3s-github`

I'm testing it right now, and with the fix I made before leaving for vacation, I'm passed the step where it was failing. So far so good, I'll keep you posted.

**Comment by fharper** [comment]
With the k3s PR, I have now an issue with the SSH key. The file is readable, and exist, but it seems like k1 can't find it.

```
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m╷\u001b[0m\u001b[0m"}
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[1m\u001b[31mError: \u001b[0m\u001b[0m\u001b[1mInvalid function argument\u001b[0m"}
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m"}
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[0m  on main.tf line 24, in module \"k3s\":"}
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m  24:         private_key = file(\u001b[4mvar.ssh_private_key\u001b[0m)\u001b[0m"}
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m    \u001b[90m├────────────────\u001b[0m"}
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[0m    \u001b[90m│\u001b[0m \u001b[1mvar.ssh_private_key\u001b[0m is \"/Users/fharper/.ssh/id_ed25519\""}
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[0m"}
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mInvalid value for \"path\" parameter: no file exists at"}
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\"/Users/fharper/.ssh/id_ed25519\"; this function works only with files that"}
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mare distributed as part of the configuration source code, so if this file"}
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mwill be created by a resource in this configuration you must instead obtain"}
{"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mthis result from an attribute of that resource."}
```

Any idea what is going on here?

I'll give a try to the GitLab one as it's been a while, to see if it's a GitHub issue, a k3s one, or probably a code 18 😅

**Comment by DrummyFloyd** [comment]
> With the k3s PR, I have now an issue with the SSH key. The file is readable, and exist, but it seems like k1 can't find it.
> 
> ```
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m╷\u001b[0m\u001b[0m"}
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[1m\u001b[31mError: \u001b[0m\u001b[0m\u001b[1mInvalid function argument\u001b[0m"}
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m"}
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[0m  on main.tf line 24, in module \"k3s\":"}
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m  24:         private_key = file(\u001b[4mvar.ssh_private_key\u001b[0m)\u001b[0m"}
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m    \u001b[90m├────────────────\u001b[0m"}
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[0m    \u001b[90m│\u001b[0m \u001b[1mvar.ssh_private_key\u001b[0m is \"/Users/fharper/.ssh/id_ed25519\""}
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[0m"}
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mInvalid value for \"path\" parameter: no file exists at"}
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\"/Users/fharper/.ssh/id_ed25519\"; this function works only with files that"}
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mare distributed as part of the configuration source code, so if this file"}
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mwill be created by a resource in this configuration you must instead obtain"}
> {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mthis result from an attribute of that resource."}
> ```
> 
> Any idea what is going on here?
> 
> I'll give a try to the GitLab one as it's been a while, to see if it's a GitHub issue, a k3s one, or probably a code 18 😅

will check this asap , will ping you on slack when it's done ) surely a template issue here like before !

**Comment by DrummyFloyd** [comment]
ok i reproduced and found the issue issue , need to discuss with k1 teams, about solutions , once i 've discussed ith them will push a hotfix for that =) 
and the template should be fine !

**Comment by maxiar** [comment]
> > With the k3s PR, I have now an issue with the SSH key. The file is readable, and exist, but it seems like k1 can't find it.
> > ```
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m╷\u001b[0m\u001b[0m"}
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[1m\u001b[31mError: \u001b[0m\u001b[0m\u001b[1mInvalid function argument\u001b[0m"}
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m"}
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[0m  on main.tf line 24, in module \"k3s\":"}
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m  24:         private_key = file(\u001b[4mvar.ssh_private_key\u001b[0m)\u001b[0m"}
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m    \u001b[90m├────────────────\u001b[0m"}
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[0m    \u001b[90m│\u001b[0m \u001b[1mvar.ssh_private_key\u001b[0m is \"/Users/fharper/.ssh/id_ed25519\""}
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\u001b[0m"}
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mInvalid value for \"path\" parameter: no file exists at"}
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0m\"/Users/fharper/.ssh/id_ed25519\"; this function works only with files that"}
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mare distributed as part of the configuration source code, so if this file"}
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mwill be created by a resource in this configuration you must instead obtain"}
> > {"level":"debug","time":"2024-06-26T17:16:44Z","message":"ERR: \u001b[31m│\u001b[0m \u001b[0mthis result from an attribute of that resource."}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any idea what is going on here?
> > I'll give a try to the GitLab one as it's been a while, to see if it's a GitHub issue, a k3s one, or probably a code 18 😅
> 
> will check this asap , will ping you on slack when it's done ) surely a template issue here like before !
> 
> EDIT: still debugging atm i don't know where this issue come from
> 
> @maxiar can you please try on your end and tell me if you can reproduce ?

Sorry for the delay, I have some problems with my cloud hosting services, but it's ready to test when you want...

**Comment by fharper** [comment]
@maxiar: wait for the next fix on this PR. As @DrummyFloyd wrote, he identified the issue, and we discussed the solutions, so a fix in coming.

**Comment by DrummyFloyd** [comment]
hot fix made here
https://github.com/kubefirst/kubefirst-api/pull/353

seems to work on my end, but will ask for some test on k1 team to confirm that =)

**Comment by fharper** [comment]
The API changes are merged, will test this PR today.

**Comment by maxiar** [comment]
Hi! I try to test the fix using this command:

```
export GITHUB_TOKEN=XXXXXX

kubefirst beta k3s create \
    --servers-args "--disable traefik,--write-kubeconfig-mode 0644" \
    --alerts-email eduardoojimenez@gmail.com \
    --domain-name maxiar.dev \
    --git-provider github \
    --servers-private-ips 10.0.1.2,10.0.1.3,10.0.1.1 \
    --servers-public-ips 65.21.63.182,95.217.216.146,37.27.15.187 \
    --ssh-privatekey ~/.ssh-tf-hetzner-cloud/id_rsa.key \
    --ssh-user root \
    --cluster-name kubefirst \
    --gitops-template-url https://github.com/DrummyFloyd/gitops-template \
    --gitops-template-branch add-k3s-github
```
    
 
but I get and error:  Error: please provide a github organization using the --github-org flag because I've a personal account (https://github.com/maxiar) is not an organizacion.. It's mandatory? When I added --github-org maxiar  but not works...

```
kubefirst beta k3s create \
    --servers-args "--disable traefik,--write-kubeconfig-mode 0644" \
    --alerts-email eduardoojimenez@gmail.com \
    --domain-name maxiar.dev \
    --git-provider github \
    --github-org maxiar \
    --servers-private-ips 10.0.1.2,10.0.1.3,10.0.1.1 \
    --servers-public-ips 65.21.63.182,95.217.216.146,37.27.15.187 \
    --ssh-privatekey ~/.ssh-tf-hetzner-cloud/id_rsa.key \
    --ssh-user root \
    --cluster-name kubefirst \
    --gitops-template-url https://github.com/DrummyFloyd/gitops-template \
    --gitops-template-branch add-k3s-github
```

Error: something went wrong calling GitHub API during org lookup, http
  status code is: 404, and response is: "{\"message\":\"Not
  Found\",\"documentation_url\":\"https://docs.github.com/rest/orgs/members#get-
  organization-membership-for-a-user\",\"status\":\"404\"}"
  
     
Can you help me? Thanks in advanced

**Comment by fharper** [comment]
> It's mandatory? When I added --github-org maxiar but not works...

It is for clouds support that aren't k3d. You can create a free one with a free account on GitHub.

**Comment by DrummyFloyd** [comment]
> > It's mandatory? When I added --github-org maxiar but not works...
> 
> It is for clouds support that aren't k3d. You can create a free one with a free account on GitHub.

+ You will need make something like this for the sshbkey 

`--ssh-pirvatekey $(cat ~/.ssh/id_rsa`

**Comment by maxiar** [comment]
> Since it's using an API code that isn't released, not used within the CLI until our next release, you also need to run it manually, or point the CLI to a local fork of main.
> 
> At that point, unless you tried kubefirst from code already, I would suggest you let us tests @maxiar , and once everything is good, we will merge and release a new kubefirst version with this new implementation.

oki...I understand..  while you test and prepare the new release.. during this time I will try to compile kuberfirst-cli, I already done, a few months ago...  

Only two questions: 
1) Do I need to use the latest version from this repo: https://github.com/kubefirst/kubefirst (main branch) ? only the kuberfirst-cli? or also de Kubefirst API https://github.com/kubefirst/kubefirst-api ?   

2) As @DrummyFloyd  tell me the dns-provider flag is mandatory, what happens if I already have all DNS working fine (managed by Hertzner DNS, not cloudfare) like console.maxiar.dev, kuberfirst.maxiar.dev, argo.maxiar.dev correctly pointed to a LoadBalancer (balancing behind the 3 publics IP where the kuberfist cluster is installed) It can be work?

Thanks!

**Comment by fharper** [comment]
> Do I need to use the latest version from this repo: [kubefirst/kubefirst](https://github.com/kubefirst/kubefirst) (main branch) ?

For the CLI, you can, in theory, use `main` or last published version as nothing was added to it for this PR. In practice, since you will need to use the latest API, you will need to run from `main` locally.

> the fix was already made or I waiting for it?

The SSH issue I had, is in theory fixed (I don't doubt Drummy when I say in theory, just that I didn't test it successfully yet) with this [commit](https://github.com/kubefirst/kubefirst-api/commit/06902d210ee6065deb8015ccd34ecea0f5b17d25) that was merged into the `main` branch of the API.

> only the kuberfirst-cli? or also de Kubefirst API [kubefirst/kubefirst-api](https://github.com/kubefirst/kubefirst-api) ?
Since a new CLI version using a new API version wasn't publish yet, you will also need to point the CLI to the latest from `main`. Once I'm done with my tests, I will update our repository docs to write how to properly test that with the CLI, as we only have instructions to use a local API version if you use the console for UI installation.

> As @DrummyFloyd tell me the dns-provider flag is mandatory,
AFAIK, it won't work as kubefirst is creating subdomains and pointing proper DNS for you and ensure it points to the right pods/nginx... in any clouds offering we have, hence why on public clouds you can choose to use their DNS or cloudflare. On k3s, since it can be created everywhere, you can only use Cloudflare. You always just need to provider the root domain name, we do the rest. With that said, you can create a free Cloudflare account which I think will let you manage one domain DNS without having to pay.

**Comment by fharper** [comment]
It may be a code 18 and I'm not using the latest API version, but when I tried I got this error (see screenshot), and no `ssh_private_key\` was in `~/.k1/kubefirst-fred/gitops/terraform/k3s/terraform.tfvars` 🤯

**Comment by maxiar** [comment]
> > > It's mandatory? When I added --github-org maxiar but not works...
> > 
> > 
> > It is for clouds support that aren't k3d. You can create a free one with a free account on GitHub.
> 
> * You will need make something like this for the sshbkey
> 
> `--ssh-privatekey $(cat ~/.ssh/id_rsa)`
> 
> and the dns-provider is mandatory

The correct way to pass the private key is: 

`--ssh-privatekey "$(cat ~/.ssh-tf-hetzner-cloud/id_rsa.key)"`

with quotes to avoid the error: 

Error: bad flag syntax: -----END Usage: executor [flags]
The -----END is indicating the end of the private key text.

**Comment by maxiar** [comment]
> > Do I need to use the latest version from this repo: [kubefirst/kubefirst](https://github.com/kubefirst/kubefirst) (main branch) ?
> 
> For the CLI, you can, in theory, use `main` or last published version as nothing was added to it for this PR. In practice, since you will need to use the latest API, you will need to run from `main` locally.
> 
> > the fix was already made or I waiting for it?
> 
> The SSH issue I had, is in theory fixed (I don't doubt Drummy when I say in theory, just that I didn't test it successfully yet) with this [commit](https://github.com/kubefirst/kubefirst-api/commit/06902d210ee6065deb8015ccd34ecea0f5b17d25) that was merged into the `main` branch of the API.
> 
> > only the kuberfirst-cli? or also de Kubefirst API [kubefirst/kubefirst-api](https://github.com/kubefirst/kubefirst-api) ?
> 
> Since a new CLI version using a new API version wasn't publish yet, you will also need to point the CLI to the latest from `main`. Once I'm done with my tests, I will update our repository docs to write how to properly test that with the CLI, as we only have instructions to use a local API version if you use the console for UI installation.
> 
> > As @DrummyFloyd tell me the dns-provider flag is mandatory,
> 
> AFAIK, it won't work as kubefirst is creating subdomains and pointing proper DNS for you and ensure it points to the right pods/nginx... in any clouds offering we have, hence why on public clouds you can choose to use their DNS or cloudflare. On k3s, since it can be created everywhere, you can only use Cloudflare. You always just need to provider the root domain name, we do the rest. With that said, you can create a free Cloudflare account which I think will let you manage one domain DNS without having to pay.


Well, in my humble contribution ...

I did all.. download, compile, and run all locally:  kuberfist & kuberfirst-api, create a cloudfare account, transfer my domain, all.. but continue no working, using the following command:

```
export GITHUB_TOKEN=XXXXXXXXX
export CF_API_TOKEN=XXXXXXXXXX

go run . beta k3s create \
    --servers-args "--disable traefik,--write-kubeconfig-mode 0644" \
    --alerts-email eduardoojimenez@gmail.com \
    --dns-provider cloudflare \
    --domain-name maxiar.dev \
    --git-provider github \
    --github-org maxiar-org \
    --servers-private-ips 10.0.1.2,10.0.1.3,10.0.1.1 \
    --servers-public-ips 65.21.63.182,95.217.216.146,37.27.15.187 \
    --ssh-privatekey "$(cat ~/.ssh-tf-hetzner-cloud/id_rsa.key)" \
    --ssh-user root \
    --cluster-name maxiar \
    --gitops-template-url https://github.com/DrummyFloyd/gitops-template \
    --gitops-template-branch add-k3s-github
```

The latest erros are:

{"level":"debug","time":"2024-07-04T21:50:07-03:00","message":"unable to reach \"https://console.kubefirst.dev/api/proxyHealth\" (15/60)"}

I attach the my logs with multiples test to analyze. 
[log_maxiar.log](https://github.com/user-attachments/files/16103702/log_maxiar.log)

NOTE: I get the same errors, using the latest kubefirst (binary, no compiled)  and pass the  --ssh-privatekey ~/.ssh/id_rsa (by file instead text), check this another logs..
[log_kubefirst.log](https://github.com/user-attachments/files/16103730/log_kubefirst.log)

Thanks!

**Comment by fharper** [comment]
> Why the cluster name is kubefirst and not maxiar (as cluster-name paramerter)?

kubefirst create an installer cluster and use k3d so k3s can use the API. It's the same for any clouds (except k3d), it all create a k3d cluster first, so it's normal.

> Why I see in the logs.... "install k3d" or "Creating k3d cluster" instead k3s, it's very confusing..

See answer to your first question.

> I get the same errors, using the latest kubefirst (binary, no compiled) and pass the --ssh-privatekey ~/.ssh/id_rsa (by file instead text), check this another logs..

It won't work, the change to receive the SSH key was done in the API, so this won't work until tou `cat` the content like you did in your first attempt.

> {"level":"debug","time":"2024-07-04T21:50:07-03:00","message":"unable to reach "[console.kubefirst.dev/api/proxyHealth](https://console.kubefirst.dev/api/proxyHealth%5C)" (15/60)"}

You didn't reach the k3s stage with this error. There is a problem with your k3d installer.

> I attach the my logs with multiples test to analyze.

Seems like this is a certificate issue, see https://docs.kubefirst.io/k3d/quick-start/install#install-the-ca-certificate-authority-of-mkcert-in-your-trusted-store . I don't think you needed to do that for the installer, just for k3d. What OS are you trying this from?

> If you need to test something, tell me... I've the local environment prepared.

For now it's good, I should be able to give it a test later today 🤞, so until I do my test, don't take more time trying yours, unless you really want to.

**Comment by fharper** [comment]
So I was able to test this PR again today. The SSH issue I had is fixed with the API PR as we thought, thanks Drummy!

I wasn't completely successful though.

1. The CLI step after "Initializing Vault" is empty. It may be related to the second point though.

CleanShot 2024-07-09 at 09 45 23@2x

2. I got stuck at this step as there is an error in the logs: it's looking for a AWS key. I assume it's an issue as one shouldn't need AWS in this process at all, unless I'm mistaken?

CleanShot 2024-07-09 at 09 49 19@2x

3. At any point, the CLI should exit with an error if there is an issue, and it cannot continue. The process is going strong after a while, even if now it's just displaying the 500 error in loop.

CleanShot 2024-07-09 at 09 45 53@2x

In any cases, right now, the #1 & #3 could be fixed by us at some point, but #2 is more a question for you @DrummyFloyd . As soon as I can, I'll give a try also with GitLab to see if it's specific to this PR or if I can reproduce everywhere with k3s.

**Comment by DrummyFloyd** [comment]
ok good, we're going forward =D ( i ported the fix to Gitlab to in this PR fyi)

like i said , in the first comment, of the PR, i wasn't really sure about TF stuff, so maybe, it come from there, 

yes please try upon GITLAB , to check if you have the same issue 

quite hard to check everything on all theses template + Tf stuff ^^

**Comment by fharper** [comment]
I didn't have time to test with GitLab, but testing with the latest fix on this PR + GitHub now.

Any ideas why you have none of the issues I get when I test!?

For GitLab, my plan was to test with the latest release, am I correct? Or should I use this PR since you added a fix here also? Just to be sure.

Unrelated, I was struggling to create the VMs before being able to test (unrelated to K3s, something based on my machine configurations), so from now on, I' gonna be able to test way faster.

**Comment by DrummyFloyd** [comment]
> I didn't have time to test with GitLab, but testing with the latest fix on this PR + GitHub now.
> 
> Any ideas why you have none of the issues I get when I test!?

because i did not test the entire mechanism ^^'

> For GitLab, my plan was to test with the latest release, am I correct? Or should I use this PR since you added a fix here also? Just to be sure.
 you have to use the template from this PR

**Comment by fharper** [comment]
So at the Vault configuration (or right after), something weird happened with GitHub. It tried to access a cluster on DigitalOcean (and really tried as Little Snitch asked me to accept or not a connection to digitalocean.com). I assumed it's some copy/paste somewhere?

CleanShot 2024-07-09 at 16 40 42@2x

**Comment by fharper** [comment]
I just tested GitLab and it reached mostly the end. I'm stuck at the "Wrapping up" step. The last log entries are "waiting for final sync wave Deployment to transition to Running" and "waiting for crossplane Deployment to be created" . The only thing I can see in the cluster is GitLab runner pods still running with errors in their logs (see screenshot).

CleanShot 2024-07-09 at 17 33 31@2x

I can access the Vault interface, but not Argo CD nor the management (console). They all give me this error.

CleanShot 2024-07-09 at 17 36 20@2x

**Comment by DrummyFloyd** [comment]
> So at the Vault configuration (or right after), something weird happened with GitHub. It tried to access a cluster on DigitalOcean (and really tried as Little Snitch asked me to accept or not a connection to digitalocean.com). I assumed it's some copy/paste somewhere?
> 
> CleanShot 2024-07-09 at 16 40 42@2x

because some tf stuff was a copy/paste from DO template, i may have missed some `Do_token` will check taht

**Comment by DrummyFloyd** [comment]
> I just tested GitLab and it reached mostly the end. I'm stuck at the "Wrapping up" step. The last log entries are "waiting for final sync wave Deployment to transition to Running" and "waiting for crossplane Deployment to be created" . The only thing I can see in the cluster is GitLab runner pods still running with errors in their logs (see screenshot).
> 
> CleanShot 2024-07-09 at 17 33 31@2x
> 
> I can access the Vault interface, but not Argo CD nor the management (console). They all give me this error.
> 
> CleanShot 2024-07-09 at 17 36 20@2x

at this point, i think something change on `kubefirst/kubefrist-api` because @jarededwards  fixed that before the K3S-gitlab was merge with everything =)

**Comment by fharper** [comment]
I doubt it's a GitLab issue, as in, how GitLab works, the product, not how we use it, since GitLab is working on other clouds.

As for GitHub, I'll give it another test hopefully today.

**Comment by fharper** [comment]
So the GitLab issue may be related to https://github.com/kubefirst/gitops-template/pull/771/files

**Comment by fharper** [comment]
I'm trying GitHub now.

**Comment by fharper** [comment]
So I ended up with nearly the same state for GitHub than GitLab. It's stuck at the "wrapping up" step, and the last log entry is waiting on crossplane deployment.

Here the state of the pods

CleanShot 2024-07-10 at 14 54 14@2x

I'll wait on this GitHub fix to test GitLab again, as I assume the token issue was fixed for GitLab Runner, but I may end up at the same place.

**Comment by fharper** [comment]
We are soooo close!

So I tried GitHub and it worked on first try: I moved passed my crossplane issue.

I tried GitLab, but ended up with a new issue (see screenshot). I will give it a second try, but I wonder if it's not one of the latest changes when we removed GitLab stuff.

CleanShot 2024-07-16 at 16 38 04@2x

**Review by fharper — APPROVED** [review]
We have an issue with Atlantis + Metaphor on GitLab, but since K3s is still in beta, and that this PR was about GitHub, we are finally good to merge and release this 🎉

Thanks a lot @DrummyFloyd & everyone who helped!

**Pull request merged**
