### PR TITLE
fix: cloudflare origin-ca-issuer chart repo and version

### PR DESCRIPTION
**Pull request by marc0olo**
as discussed on slack :-)

ref: https://github.com/cloudflare/origin-ca-issuer/issues/97#issuecomment-1897139971

### CODE REVIEW

**Review by CristhianF7 — APPROVED** [review]

**Comment by johndietz** [comment]
@marc0olo can we bother you to edit your commit to add signature to the commit?

**Comment by marc0olo** [comment]
> @marc0olo can we bother you to edit your commit to add signature to the commit?

done ;-)

**Comment by marc0olo** [comment]
though I just see it is expired 🤔  🙈 even though I extended it. strange

**Comment by johndietz** [comment]
looking good on our side, thanks a bunch @marc0olo !!

**Pull request merged**
